2021-03-01T03:59:32: PM2 log: ===============================================================================
2021-03-01T03:59:32: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
2021-03-01T03:59:32: PM2 log: Time                 : Mon Mar 01 2021 03:59:32 GMT-0400 (Amazon Standard Time)
2021-03-01T03:59:32: PM2 log: PM2 version          : 4.5.5
2021-03-01T03:59:32: PM2 log: Node.js version      : 14.15.4
2021-03-01T03:59:32: PM2 log: Current arch         : arm
2021-03-01T03:59:32: PM2 log: PM2 home             : /data/data/com.termux/files/home/.pm2
2021-03-01T03:59:32: PM2 log: PM2 PID file         : /data/data/com.termux/files/home/.pm2/pm2.pid
2021-03-01T03:59:32: PM2 log: RPC socket file      : /data/data/com.termux/files/home/.pm2/rpc.sock
2021-03-01T03:59:32: PM2 log: BUS socket file      : /data/data/com.termux/files/home/.pm2/pub.sock
2021-03-01T03:59:32: PM2 log: Application log path : /data/data/com.termux/files/home/.pm2/logs
2021-03-01T03:59:32: PM2 log: Worker Interval      : 30000
2021-03-01T03:59:32: PM2 log: Process dump file    : /data/data/com.termux/files/home/.pm2/dump.pm2
2021-03-01T03:59:32: PM2 log: Concurrent actions   : 2
2021-03-01T03:59:32: PM2 log: SIGTERM timeout      : 1600
2021-03-01T03:59:32: PM2 log: ===============================================================================
2021-03-01T03:59:33: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T03:59:33: PM2 log: App [index:0] online
2021-03-01T03:59:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T03:59:33: PM2 error: Error while getting PAGESIZE Error: Command failed: getconf PAGESIZE
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf PAGESIZE'
}
2021-03-01T03:59:33: PM2 error: Error while getting CLK_TCK Error: Command failed: getconf CLK_TCK
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf CLK_TCK'
}
2021-03-01T04:00:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:00:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:01:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:01:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:02:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:02:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:03:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:03:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:04:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:04:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:05:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:05:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:06:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:06:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:07:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:07:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:08:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:08:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:09:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:09:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:10:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:10:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:11:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:11:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:12:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:12:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:13:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:13:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:14:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:14:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:15:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:15:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:16:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:16:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:17:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:17:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:18:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:18:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:19:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:19:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:20:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:20:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:21:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:21:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:22:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:22:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:23:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:23:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:24:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:24:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:25:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:25:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:26:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:26:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:27:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:27:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:28:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:28:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:29:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:29:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:30:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:30:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:31:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:31:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:32:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:32:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:33:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:33:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:34:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:34:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:35:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:35:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:36:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:36:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:37:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:37:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:38:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:38:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:39:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:39:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:40:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:40:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:41:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:41:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:42:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:42:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:43:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:43:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:44:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:44:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:45:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:45:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:46:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:46:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:47:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:47:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:48:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:48:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:49:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:49:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:50:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:50:14: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-01T04:50:14: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T04:50:14: PM2 log: App [index:0] online
2021-03-01T04:50:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:51:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:51:28: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-01T04:51:28: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T04:51:28: PM2 log: App [index:0] online
2021-03-01T04:51:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:52:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:52:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:53:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:53:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:54:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:54:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:55:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:55:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:56:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:56:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:57:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:57:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:58:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:58:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:59:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T04:59:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:00:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:00:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:01:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:01:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:02:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:02:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:03:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:03:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:04:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:04:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:05:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:05:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:06:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:06:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:07:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:07:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:08:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:08:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:09:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:09:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:10:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:10:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:11:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:11:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:12:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:12:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:13:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:13:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:14:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:14:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:15:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:15:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:16:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:16:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:17:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:17:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:18:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:18:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:19:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:19:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:20:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:20:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:21:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:21:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:22:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:22:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:23:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:23:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:24:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:24:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:25:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:25:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:26:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:26:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:27:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:27:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:28:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:28:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:31:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:34:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:35:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:38:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:39:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:40:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:41:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:43:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:45:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:48:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:53:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:58:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T05:58:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:00:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:03:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:07:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:12:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:18:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:21:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:23:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:27:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:34:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:35:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:36:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:37:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:38:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:38:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:39:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:39:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:40:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:40:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:41:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:41:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:42:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:42:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:43:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:43:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:44:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:44:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:45:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:45:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:46:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:46:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:47:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:47:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:50:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:53:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:57:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T06:59:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:02:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:06:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:10:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:11:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:12:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:12:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:13:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:13:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:14:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:14:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:15:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:15:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:16:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:16:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:17:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:17:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:18:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:18:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:19:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:19:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:20:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:20:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:21:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:21:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:22:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:22:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:23:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:23:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:24:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:24:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:25:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:25:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:26:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:26:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:27:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:27:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:28:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:28:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:29:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:29:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:30:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:30:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:31:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:31:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:32:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:32:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:33:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:33:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:34:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:34:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:35:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:35:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:36:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:36:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:37:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:37:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:38:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:38:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:39:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:39:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:40:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:40:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:41:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:41:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:42:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:42:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:43:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:43:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:44:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:44:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:45:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:45:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:46:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:46:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:47:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:47:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:48:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:48:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:49:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:49:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:50:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:50:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:51:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:51:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:52:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:52:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:53:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:53:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:54:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:54:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:55:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:55:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:56:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:56:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:57:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:57:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:58:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:58:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:59:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T07:59:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:00:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:00:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:01:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:01:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:02:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:02:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:03:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:03:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:04:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:04:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:05:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:05:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:06:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:06:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:07:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:07:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:08:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:08:15: PM2 log: App [index:0] exited with code [0] via signal [SIGINT]
2021-03-01T08:08:15: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T08:08:15: PM2 log: App [index:0] online
2021-03-01T08:08:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:09:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:09:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:10:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:10:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:11:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:11:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:12:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:12:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:13:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:13:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:14:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:14:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:15:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:15:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:15:47: PM2 log: App [index:0] exited with code [0] via signal [SIGINT]
2021-03-01T08:15:47: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T08:15:47: PM2 log: App [index:0] online
2021-03-01T08:16:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:16:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:17:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:17:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:18:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:18:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:19:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:19:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:20:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:20:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:21:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:21:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:22:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:22:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:23:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:23:24: PM2 log: App [index:0] exited with code [0] via signal [SIGINT]
2021-03-01T08:23:24: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T08:23:24: PM2 log: App [index:0] online
2021-03-01T08:23:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:24:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:24:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:25:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:25:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:26:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:26:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:27:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:27:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:28:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:28:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:29:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:29:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:30:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:30:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:30:58: PM2 log: App [index:0] exited with code [0] via signal [SIGINT]
2021-03-01T08:30:58: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T08:30:58: PM2 log: App [index:0] online
2021-03-01T08:31:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:31:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:32:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:32:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:33:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:33:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:34:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:34:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:35:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:35:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:36:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:36:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:37:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:37:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:38:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:38:31: PM2 log: App [index:0] exited with code [0] via signal [SIGINT]
2021-03-01T08:38:31: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T08:38:31: PM2 log: App [index:0] online
2021-03-01T08:38:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:39:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:39:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:40:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:40:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:41:05: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-01T08:41:06: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T08:41:06: PM2 log: App [index:0] online
2021-03-01T08:41:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:41:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:42:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:42:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:43:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:43:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:44:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:44:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:45:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:45:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:46:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:46:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:47:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:47:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:48:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:48:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:49:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:49:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:50:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:50:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:51:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:51:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:52:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:52:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:53:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:53:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:54:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:54:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:55:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:55:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:56:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:56:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:57:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:57:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:58:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:58:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:59:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T08:59:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:00:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:00:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:01:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:01:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:02:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:02:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:03:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:03:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:04:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:04:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:05:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:05:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:06:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:06:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:07:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:07:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:08:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:08:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:09:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:09:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:10:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:10:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:11:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:11:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:12:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:12:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:13:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:13:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:14:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:14:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:15:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:15:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:16:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:16:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:17:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:17:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:18:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:18:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:19:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:19:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:20:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:20:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:21:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:21:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:22:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:22:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:23:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:23:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:24:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:24:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:25:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:25:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:26:04: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-01T09:26:04: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T09:26:04: PM2 log: App [index:0] online
2021-03-01T09:26:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:26:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:27:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:27:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:28:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:28:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:29:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:29:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:30:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:30:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:31:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:31:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:32:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:32:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:33:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:33:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:34:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:34:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:35:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:35:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:36:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:36:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:37:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:37:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:38:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:38:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:39:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:39:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:40:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:40:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:41:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:41:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:42:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:42:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:43:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:43:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:44:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:44:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:45:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:45:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:46:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:46:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:47:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:47:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:48:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:48:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:49:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:49:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:50:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:50:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:51:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:51:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:52:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:52:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:53:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:53:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:54:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:54:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:55:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:55:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:56:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:56:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:57:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:57:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:58:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:58:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:59:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T09:59:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:00:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:00:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:01:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:01:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:02:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:02:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:03:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:03:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:04:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:04:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:05:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:05:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:06:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:06:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:07:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:07:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:08:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:08:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:08:47: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-01T10:08:47: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T10:08:47: PM2 log: App [index:0] online
2021-03-01T10:09:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:09:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:10:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:10:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:11:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:11:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:12:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T10:12:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:08:41: PM2 log: ===============================================================================
2021-03-01T19:08:42: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
2021-03-01T19:08:42: PM2 log: Time                 : Mon Mar 01 2021 19:08:42 GMT-0400 (Amazon Standard Time)
2021-03-01T19:08:42: PM2 log: PM2 version          : 4.5.5
2021-03-01T19:08:42: PM2 log: Node.js version      : 14.15.4
2021-03-01T19:08:42: PM2 log: Current arch         : arm
2021-03-01T19:08:42: PM2 log: PM2 home             : /data/data/com.termux/files/home/.pm2
2021-03-01T19:08:42: PM2 log: PM2 PID file         : /data/data/com.termux/files/home/.pm2/pm2.pid
2021-03-01T19:08:42: PM2 log: RPC socket file      : /data/data/com.termux/files/home/.pm2/rpc.sock
2021-03-01T19:08:42: PM2 log: BUS socket file      : /data/data/com.termux/files/home/.pm2/pub.sock
2021-03-01T19:08:42: PM2 log: Application log path : /data/data/com.termux/files/home/.pm2/logs
2021-03-01T19:08:42: PM2 log: Worker Interval      : 30000
2021-03-01T19:08:42: PM2 log: Process dump file    : /data/data/com.termux/files/home/.pm2/dump.pm2
2021-03-01T19:08:42: PM2 log: Concurrent actions   : 2
2021-03-01T19:08:42: PM2 log: SIGTERM timeout      : 1600
2021-03-01T19:08:42: PM2 log: ===============================================================================
2021-03-01T19:08:42: PM2 log: App [index:0] starting in -fork mode-
2021-03-01T19:08:42: PM2 log: App [index:0] online
2021-03-01T19:08:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:08:42: PM2 error: Error while getting CLK_TCK Error: Command failed: getconf CLK_TCK
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf CLK_TCK'
}
2021-03-01T19:08:43: PM2 error: Error while getting PAGESIZE Error: Command failed: getconf PAGESIZE
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf PAGESIZE'
}
2021-03-01T19:09:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:09:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:10:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:10:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:11:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:11:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:12:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:12:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:13:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:13:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:14:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:14:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:15:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:15:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:16:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:16:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:17:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:17:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:18:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:18:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:19:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:19:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:20:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:20:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:21:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:21:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:22:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:22:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:23:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:23:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:24:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:24:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:25:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:25:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:26:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:26:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:27:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:27:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:28:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:28:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:29:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:29:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:30:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:30:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:31:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:31:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:32:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:32:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:33:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:33:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:34:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:34:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:35:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:35:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:36:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:37:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:38:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:38:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:39:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:39:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:40:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:40:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:41:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:41:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:42:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:42:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:43:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:43:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:44:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:44:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:45:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:45:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:46:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:46:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:47:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:47:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:48:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:48:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:49:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:49:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:50:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:50:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:51:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:51:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:52:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:52:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:53:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:53:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:54:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:54:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:55:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:55:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:56:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:56:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:57:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:57:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:58:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:58:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:59:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T19:59:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:00:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:00:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:01:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:01:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:02:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:02:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:03:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:03:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:04:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:04:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:05:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:05:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:06:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:06:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:07:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:07:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:08:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:08:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:09:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:09:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:10:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:10:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:11:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:11:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:12:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:12:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:13:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:13:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:14:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:14:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:15:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:15:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:16:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:16:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:17:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:17:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:18:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:18:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:19:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:19:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:20:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:20:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:21:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:22:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:22:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:23:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:23:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:24:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:24:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:25:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:25:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:26:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:26:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:27:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:28:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:28:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:29:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:29:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:30:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:30:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:31:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:31:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:32:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:32:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:33:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:33:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:34:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:34:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:35:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:35:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:36:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:36:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:37:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:37:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:38:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:38:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:39:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:39:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:40:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:41:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:41:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:42:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:42:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:43:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:43:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:44:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:44:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:45:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:45:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:46:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:46:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:47:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:47:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:48:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:48:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:49:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:49:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:50:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:50:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:51:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:51:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:52:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:52:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:53:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:53:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:54:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:54:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:55:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:55:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:56:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:56:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:57:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:57:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:58:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:58:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:59:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T20:59:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:00:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:00:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:01:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:01:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:02:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:02:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:03:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:03:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:04:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:04:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:05:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:05:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:06:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:06:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:07:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:07:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:08:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:08:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:09:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:09:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:10:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:10:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:11:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:11:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:12:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:12:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:13:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:13:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:14:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:14:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:15:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:15:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:16:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:16:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:17:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:17:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:18:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:21:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:23:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:25:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:27:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:28:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:30:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:32:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:33:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:37:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:40:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:41:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:43:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:46:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:49:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:51:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:54:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:55:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:57:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T21:58:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:00:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:02:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:05:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:07:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:08:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:08:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:09:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:10:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:11:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:12:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:13:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:15:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:18:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:20:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:24:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:27:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:27:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:28:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:28:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:29:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:29:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:30:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:30:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:31:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:31:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:32:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:32:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:33:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:33:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:34:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:34:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:35:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:35:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:36:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:36:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:37:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:37:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:38:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:38:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:39:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:39:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:40:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:40:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:41:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:41:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:42:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:42:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:43:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:43:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:44:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:44:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:45:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:45:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:46:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:46:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:47:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:47:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:48:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:48:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:49:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:49:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:50:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:50:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:51:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:51:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:52:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:52:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:53:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:53:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:54:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:54:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:55:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:55:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:56:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:56:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:57:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:57:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:58:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:58:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:59:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T22:59:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:00:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:00:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:01:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:01:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:02:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:02:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:03:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:03:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:04:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:04:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:05:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:05:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:06:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:06:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-01T23:07:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
